site_name: Martin Weise
site_author: Martin Weise
copyright: CC BY 4.0 Martin Weise
extra:
  homepage: https://martinweise.at
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/martin-weise-094273218/
    - icon: fontawesome/regular/id-card
      link: https://isni.org/isni/0000000506791090
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=uMn2MpgAAAAJ
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-4216-302X
nav:
  - Home: 'index.md'
  - publications.md
  - projects.md
  - teaching.md
  - contact.md
extra_css:
  - stylesheets/extra.css
theme:
  favicon: images/asterisk-solid.svg
  language: en
  font:
    text: IBM Plex Serif
    code: IBM Plex Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: blue grey
      secondary: red
      font:
        code: Roboto Mono
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: black
      secondary: red
      font:
        code: Roboto Mono
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  name: material
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
