site_name: Martin Weise
site_author: Martin Weise
copyright: CC BY 4.0 Martin Weise
extra:
  homepage: https://martinweise.at
nav:
  - Home: 'index.md'
  - publications.md
  - projects.md
  - teaching.md
  - contact.md
extra_css:
  - stylesheets/extra.css
theme:
  favicon: images/asterisk-solid.svg
  language: en
  font:
    text: IBM Plex Serif
    code: IBM Plex Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: blue grey
      font:
        code: Roboto Mono
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: indigo
      font:
        code: Roboto Mono
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  name: material
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
